### ISSUE TITLE
New version v1.32.3498.90 cba2e5

### ISSUE THREAD

**Issue by rfdrew** [simonmicro/Pritunl-Fake-API#28]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/20803599/232415832-54e30ea9-a274-4b86-9872-a84f02ff9ff5.png">
v1.32.3498.90 cba2e5

**Comment by royalhaze** [comment]
same issue , i try it on many version and still not working

**Comment by royalhaze** [comment]
> same issue , i try it on many version and still not working

this bug happened because browser unable to load subscription style file in some case 
/subscription/styles/enterprise_plus/1003235044068.css
this page response with internal server error

**Comment by simonmicro** [comment]
Wait - internal server error on Python or on the fake-api backend?

**Comment by PhotonBolt** [comment]
I believe it's Python error, as you can see the request came from my server
![error](https://user-images.githubusercontent.com/21114760/233791010-fe41e2e8-3571-4d64-a616-5fc21971de8b.png)

**Comment by PhotonBolt** [comment]
Although I have updated Pritunl to `v1.32.3504.68` and still has the same error

**Comment by royalhaze** [comment]
> Although I have updated Pritunl to `v1.32.3504.68` and still has the same error

just use this installation script 
[royalhaze/pritunl-install](https://github.com/royalhaze/pritunl-install)

it use v1.30.3108.50

**Comment by Vlad1mir-D** [comment]
This issue was caused by these two commits and some invisible updates on the real API side:
- https://github.com/pritunl/pritunl/commit/d523e4869894240ef105e3c3f3787513b4dc5559
- https://github.com/pritunl/pritunl/commit/c7bb723965407cf8061b9bbaf3c903c3dc369941

So the latest version which works properly with the current version of Fake API is https://github.com/pritunl/pritunl/releases/tag/1.32.3457.59
There is a chance I'll update API if someone won't make it before but it's definitely going take a loong while as I'm currently I'm very limited in my spare time.

**Comment by Vlad1mir-D** [comment]
Ah, it seems there are additional commits which prevents proper interaction with an API:
- https://github.com/pritunl/pritunl/commit/0b600799d2dcee23b54538e0fdb300d25d67921d
- https://github.com/pritunl/pritunl/commit/4677814f88ac5aa5c708b6bcbc6dc9ef96c73d0a

So currently we're capped at https://github.com/pritunl/pritunl/releases/tag/1.30.3431.73

**Comment by simonmicro** [comment]
Oh boi. @Vlad1mir-D any PRs are more than welcome - as I also have very limited time at the moment. But I'm pretty sure, that we can figure something out...

**Comment by Vlad1mir-D** [comment]
I've managed to implement a dirty workaround so it's time to fix a few things and I'll be able to publish a solution for 1.32.3457.59 but I can't give any ETA.

**Comment by niyazialpay** [comment]
I'm having trouble same thing

**Comment by tobiasredel** [comment]
I am also looking for a fix. Great effort. Thanks @simonmicro

**Comment by niyazialpay** [comment]
I found that the issue is caused by the CSS file at the "/subscription/styles/enterprise_plus/1003235334094.css" address returning a 500 error. I noticed that this address is defined in the file "/usr/lib/pritunl/usr/lib/python3.9/site-packages/pritunl/handlers/subscription.py" with the line "@app.app.route('/subscription/styles/<plan>/<ver>.css', methods=['GET'])". To resolve the problem, I commented out the entire "if styles['etag'] and styles['data']" command block in this route definition and restarted the service, which fixed the issue. You can create a function that can be used to remove or comment out this section after the replace step in the Fake API script for intervention.

**Comment by Vlad1mir-D** [comment]
@niyazialpay just read the https://github.com/simonmicro/Pritunl-Fake-API/issues/28#issuecomment-1528648854

**Comment by simonmicro** [comment]
Done - fixed and live.

**Comment by Vlad1mir-D** [comment]
Thanks @simonmicro!
I'm glad my code helped a little :)

**Comment by rfdrew** [comment]
many thanks!!!!

**Comment by amirhmoradi** [comment]
I am still facing this issue on latest pritunl v1.32.3552.76 3f54d8

**Comment by simonmicro** [comment]
@amirhmoradi Could you further describe your setup please? It seems strange that you report this error, while most users are happy. Could it be that your PHP version is outdated?

**Comment by amirhmoradi** [comment]
@simonmicro it was my error, sorry. 
I had an old version running on the server and mixed up my setup.
Everything seems to be working fine indeed. Thanks for the great work.
